logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.HttpLogging: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: TRACE
    org.springframework.cloud.gateway: TRACE

spring:
  application:
    name: api-gateway

  main:
    allow-bean-definition-overriding: true

  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: 761045752544-sgrh2it011ilh29215b8a0f4bi6ekc4d.apps.googleusercontent.com
            authorization-grant-type: authorization_code
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, email, profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

